package main

type Response struct {
	Status    string `json:"status,omitempty"`
	Message   any    `json:"message,omitempty"`
	Data      Data   `json:"data,omitempty"`
	HasErrors bool   `json:"hasErrors,omitempty"`
}

type Subject struct {
	ID                       any    `json:"id,omitempty"`
	SubjectCode              any    `json:"subjectCode,omitempty"`
	Name                     string `json:"name,omitempty"`
	EngName                  any    `json:"engName,omitempty"`
	PermissionStartDate      any    `json:"permissionStartDate,omitempty"`
	PermissionEndDate        any    `json:"permissionEndDate,omitempty"`
	IsPermission             any    `json:"isPermission,omitempty"`
	IsPermissionType         any    `json:"isPermissionType,omitempty"`
	Credit                   any    `json:"credit,omitempty"`
	IsCreditRecognition      any    `json:"isCreditRecognition,omitempty"`
	TotalWeeks               int    `json:"totalWeeks,omitempty"`
	ExamWeeks                any    `json:"examWeeks,omitempty"`
	LessonsPerWeek           int    `json:"lessonsPerWeek,omitempty"`
	CurrentWeek              any    `json:"currentWeek,omitempty"`
	TotalLessons             any    `json:"totalLessons,omitempty"`
	IsLiberalArts            any    `json:"isLiberalArts,omitempty"`
	Sample                   any    `json:"sample,omitempty"`
	Lesson                   any    `json:"lesson,omitempty"`
	Outline                  any    `json:"outline,omitempty"`
	Goal                     any    `json:"goal,omitempty"`
	Teacher                  any    `json:"teacher,omitempty"`
	FullTimeTeacher          any    `json:"fullTimeTeacher,omitempty"`
	Remark                   any    `json:"remark,omitempty"`
	TuitionFee               any    `json:"tuitionFee,omitempty"`
	IsRecommended            any    `json:"isRecommended,omitempty"`
	IsEnabled                any    `json:"isEnabled,omitempty"`
	IsSupportMobile          any    `json:"isSupportMobile,omitempty"`
	Author                   any    `json:"author,omitempty"`
	IsAddedEvaluation        any    `json:"isAddedEvaluation,omitempty"`
	IsAddedLessons           any    `json:"isAddedLessons,omitempty"`
	IsMajor                  any    `json:"isMajor,omitempty"`
	IsSatisfyQuestions       any    `json:"isSatisfyQuestions,omitempty"`
	AttendCount              any    `json:"attendCount,omitempty"`
	Major                    any    `json:"major,omitempty"`
	Majors                   any    `json:"majors,omitempty"`
	AssociateTeachers        any    `json:"associateTeachers,omitempty"`
	ManageTeachers           any    `json:"manageTeachers,omitempty"`
	MasterTextbooks          any    `json:"masterTextbooks,omitempty"`
	SubTextbooks             any    `json:"subTextbooks,omitempty"`
	ReferenceTextbooks       any    `json:"referenceTextbooks,omitempty"`
	TextBooks                any    `json:"textBooks,omitempty"`
	CompletedScore           any    `json:"completedScore,omitempty"`
	CompletedAttendance      int    `json:"completedAttendance,omitempty"`
	MidtermRatio             any    `json:"midtermRatio,omitempty"`
	FinalRatio               any    `json:"finalRatio,omitempty"`
	AssignmentRatio          any    `json:"assignmentRatio,omitempty"`
	AttendanceRatio          any    `json:"attendanceRatio,omitempty"`
	ParticipationRatio       any    `json:"participationRatio,omitempty"`
	DistributionRatio90Over  any    `json:"distributionRatio90Over,omitempty"`
	DistributionRatio80Over  any    `json:"distributionRatio80Over,omitempty"`
	DistributionRatio70Over  any    `json:"distributionRatio70Over,omitempty"`
	DistributionRatio60Over  any    `json:"distributionRatio60Over,omitempty"`
	DistributionRatio60Under any    `json:"distributionRatio60Under,omitempty"`
	ObjectionStartDay        any    `json:"objectionStartDay,omitempty"`
	ObjectionEndDay          any    `json:"objectionEndDay,omitempty"`
	FinishDay                any    `json:"finishDay,omitempty"`
	IsAttendanceExamWeeks    bool   `json:"isAttendanceExamWeeks,omitempty"`
	Exams                    any    `json:"exams,omitempty"`
	Assignments              any    `json:"assignments,omitempty"`
	Participations           any    `json:"participations,omitempty"`
	LearningContest          any    `json:"learningContest,omitempty"`
	SelfIntroduction         any    `json:"selfIntroduction,omitempty"`
	LearningGoal             any    `json:"learningGoal,omitempty"`
	Dictation                any    `json:"dictation,omitempty"`
	Forums                   any    `json:"forums,omitempty"`
	TeamProjects             any    `json:"teamProjects,omitempty"`
	Reflections              any    `json:"reflections,omitempty"`
	Board                    any    `json:"board,omitempty"`
	LectureAssessment        any    `json:"lectureAssessment,omitempty"`
	Lessons                  any    `json:"lessons,omitempty"`
	Course                   any    `json:"course,omitempty"`
	Courses                  any    `json:"courses,omitempty"`
	HasParticipations        any    `json:"hasParticipations,omitempty"`
	TeacherType              any    `json:"teacherType,omitempty"`
	Categories               any    `json:"categories,omitempty"`
	SatisfyQuestions         any    `json:"satisfyQuestions,omitempty"`
	SatisfyQuestion          any    `json:"satisfyQuestion,omitempty"`
	GreetingStartDay         any    `json:"greetingStartDay,omitempty"`
	GreetingEndDay           any    `json:"greetingEndDay,omitempty"`
	BulletinStartDay         any    `json:"bulletinStartDay,omitempty"`
	BulletinEndDay           any    `json:"bulletinEndDay,omitempty"`
	ObjectionWorkStartDay    any    `json:"objectionWorkStartDay,omitempty"`
	ObjectionWorkEndDay      any    `json:"objectionWorkEndDay,omitempty"`
	RelativeYear             any    `json:"relativeYear,omitempty"`
	RelativeSemester         any    `json:"relativeSemester,omitempty"`
	RelativeSequence         any    `json:"relativeSequence,omitempty"`
	RelativeCourseID         any    `json:"relativeCourseId,omitempty"`
	RelativeClassID          any    `json:"relativeClassId,omitempty"`
	RelativeTotalCount       any    `json:"relativeTotalCount,omitempty"`
	FinalScoreAdd            any    `json:"finalScoreAdd,omitempty"`
	EngNameCnt               any    `json:"engNameCnt,omitempty"`
	IsRegular                any    `json:"isRegular,omitempty"`
	RegularRatio1            any    `json:"regularRatio1,omitempty"`
	RegularRatio2            any    `json:"regularRatio2,omitempty"`
	Type                     any    `json:"type,omitempty"`
	TotalStudyTime           any    `json:"totalStudyTime,omitempty"`
	GenericKey               any    `json:"genericKey,omitempty"`
	CompletionDivision       string `json:"completionDivision,omitempty"`
	CompletionDivisionName   string `json:"completionDivisionName,omitempty"`
}
type Exam struct {
	ID                           int    `json:"id,omitempty"`
	Course                       any    `json:"course,omitempty"`
	Subject                      any    `json:"subject,omitempty"`
	Week                         any    `json:"week,omitempty"`
	Type                         string `json:"type,omitempty"`
	StartDay                     any    `json:"startDay,omitempty"`
	EndDay                       any    `json:"endDay,omitempty"`
	SupplementaryStartDay        any    `json:"supplementaryStartDay,omitempty"`
	SupplementaryEndDay          any    `json:"supplementaryEndDay,omitempty"`
	StartDate                    any    `json:"startDate,omitempty"`
	EndDate                      any    `json:"endDate,omitempty"`
	IsSupplementary              bool   `json:"isSupplementary,omitempty"`
	ExamState                    any    `json:"examState,omitempty"`
	ApplyState                   any    `json:"applyState,omitempty"`
	ChoiceCount                  any    `json:"choiceCount,omitempty"`
	AnswerCount                  any    `json:"answerCount,omitempty"`
	SupplementaryStartDate       any    `json:"supplementaryStartDate,omitempty"`
	SupplementaryEndDate         any    `json:"supplementaryEndDate,omitempty"`
	ConstructionCount            int    `json:"constructionCount,omitempty"`
	AnswerAcceptedWaitingCount   any    `json:"answerAcceptedWaitingCount,omitempty"`
	AnswerApprovedWaitingCount   any    `json:"answerApprovedWaitingCount,omitempty"`
	AnswerApprovedQuestionCount  any    `json:"answerApprovedQuestionCount,omitempty"`
	AnswerDiscardedQuestionCount any    `json:"answerDiscardedQuestionCount,omitempty"`
	ChoiceAcceptedWaitingCount   any    `json:"choiceAcceptedWaitingCount,omitempty"`
	ChoiceApprovedWaitingCount   any    `json:"choiceApprovedWaitingCount,omitempty"`
	ChoiceApprovedQuestionCount  any    `json:"choiceApprovedQuestionCount,omitempty"`
	ChoiceDiscardedQuestionCount any    `json:"choiceDiscardedQuestionCount,omitempty"`
	ScarcityCount                int    `json:"scarcityCount,omitempty"`
	LevelCount                   int    `json:"levelCount,omitempty"`
	Question                     any    `json:"question,omitempty"`
	Constructions                any    `json:"constructions,omitempty"`
	Paper                        any    `json:"paper,omitempty"`
	Papers                       any    `json:"papers,omitempty"`
	IsImminenteDeadline          any    `json:"isImminenteDeadline,omitempty"`
	IsLess5Days                  any    `json:"isLess5Days,omitempty"`
	FinishDate                   any    `json:"finishDate,omitempty"`
	IsFinished                   any    `json:"isFinished,omitempty"`
	IsStarted                    any    `json:"isStarted,omitempty"`
	Score                        any    `json:"score,omitempty"`
	EvaluationStartDay           any    `json:"evaluationStartDay,omitempty"`
	EvaluationEndDay             any    `json:"evaluationEndDay,omitempty"`
	EvaluationStartDate          any    `json:"evaluationStartDate,omitempty"`
	EvaluationEndDate            any    `json:"evaluationEndDate,omitempty"`
	EvaluationSubject            any    `json:"evaluationSubject,omitempty"`
	JusticeID                    any    `json:"justice_id,omitempty"`
	JusticeUserID                any    `json:"justice_user_id,omitempty"`
	JusticeContents              any    `json:"justice_contents,omitempty"`
	JusticeAdminID               any    `json:"justice_admin_id,omitempty"`
	JusticeDate                  any    `json:"justiceDate,omitempty"`
	JusticeCreatedOn             any    `json:"justice_created_on,omitempty"`
	ReservationCreatedOn         any    `json:"reservation_created_on,omitempty"`
	IsReservation                any    `json:"is_reservation,omitempty"`
	IsPaper                      any    `json:"is_paper,omitempty"`
	ReservationContents          any    `json:"reservation_contents,omitempty"`
	IsJustice                    any    `json:"is_justice,omitempty"`
	IsSupplementaryExamEnd       any    `json:"is_supplementary_exam_end,omitempty"`
	IsExamEnd                    any    `json:"is_exam_end,omitempty"`
	RegularWaitngCount           any    `json:"regularWaitngCount,omitempty"`
	RegularQuestionCount         any    `json:"regularQuestionCount,omitempty"`
	ExamRegularStartDate         any    `json:"examRegularStartDate,omitempty"`
	ExamRegularEndDate           any    `json:"examRegularEndDate,omitempty"`
	NonRegularWeek               any    `json:"non_regular_week,omitempty"`
	NonRegular1EndWeek           any    `json:"non_regular_1end_week,omitempty"`
	NonRegular2EndWeek           any    `json:"non_regular_2end_week,omitempty"`
	TypeName                     string `json:"typeName,omitempty"`
	GenericKey                   int    `json:"genericKey,omitempty"`
}

type CourseLesson struct {
	ID                        int    `json:"id,omitempty"`
	Position                  int    `json:"position,omitempty"`
	Lesson                    Lesson `json:"lesson,omitempty"`
	AttendancePeriodStartDate int64  `json:"attendancePeriodStartDate,omitempty"`
	AttendancePeriodEndDate   int64  `json:"attendancePeriodEndDate,omitempty"`
	Course                    any    `json:"course,omitempty"`
	Subject                   any    `json:"subject,omitempty"`
	Week                      int    `json:"week,omitempty"`
	DoubleWeek                any    `json:"doubleWeek,omitempty"`
	NoteCount                 any    `json:"noteCount,omitempty"`
	Notifier                  any    `json:"notifier,omitempty"`
	AttendanceType            any    `json:"attendanceType,omitempty"`
	IsInprogress              any    `json:"isInprogress,omitempty"`
	GenericKey                int    `json:"genericKey,omitempty"`
	Progressed                bool   `json:"progressed,omitempty"`
	IsPast                    bool   `json:"isPast,omitempty"`
}
type Attendances struct {
	LogID                 any          `json:"logId,omitempty"`
	Course                Course       `json:"course,omitempty"`
	CourseLesson          CourseLesson `json:"courseLesson,omitempty"`
	User                  any          `json:"user,omitempty"`
	FinishedPageCount     int          `json:"finishedPageCount,omitempty"`
	LearningStartOn       any          `json:"learningStartOn,omitempty"`
	LearningEndOn         any          `json:"learningEndOn,omitempty"`
	FinishedLearningTime  int          `json:"finishedLearningTime,omitempty"`
	LearningDeviceType    any          `json:"learningDeviceType,omitempty"`
	Type                  any          `json:"type,omitempty"`
	Reason                any          `json:"reason,omitempty"`
	ResolvedQuestionCount int          `json:"resolvedQuestionCount,omitempty"`
	IP                    any          `json:"ip,omitempty"`
	Mac                   any          `json:"mac,omitempty"`
	ElapsedTime           any          `json:"elapsedTime,omitempty"`
	IsAttendance          any          `json:"isAttendance,omitempty"`
	TotalFinishPages      int          `json:"totalFinishPages,omitempty"`
	LearningChk           any          `json:"learningChk,omitempty"`
	RnStartDate1          any          `json:"rnStartDate1,omitempty"`
	RnEndDate1            any          `json:"rnEndDate1,omitempty"`
	RnStartDate2          any          `json:"rnStartDate2,omitempty"`
	RnEndDate2            any          `json:"rnEndDate2,omitempty"`
	RnStartDate3          any          `json:"rnStartDate3,omitempty"`
	RnEndDate3            any          `json:"rnEndDate3,omitempty"`
	RnStartDate4          any          `json:"rnStartDate4,omitempty"`
	RnEndDate4            any          `json:"rnEndDate4,omitempty"`
	RnStartDate5          any          `json:"rnStartDate5,omitempty"`
	RnEndDate5            any          `json:"rnEndDate5,omitempty"`
	RnStartDate6          any          `json:"rnStartDate6,omitempty"`
	RnEndDate6            any          `json:"rnEndDate6,omitempty"`
	RnStartDate7          any          `json:"rnStartDate7,omitempty"`
	RnEndDate7            any          `json:"rnEndDate7,omitempty"`
	RnStartDate8          any          `json:"rnStartDate8,omitempty"`
	RnEndDate8            any          `json:"rnEndDate8,omitempty"`
	CategoryID            any          `json:"categoryId,omitempty"`
	MajorID               any          `json:"majorId,omitempty"`
	MajorType             any          `json:"majorType,omitempty"`
	CourseLessonCnt       any          `json:"courseLessonCnt,omitempty"`
	AttendanceCnt         any          `json:"attendanceCnt,omitempty"`
	TypeName              any          `json:"typeName,omitempty"`
	GenericKey            any          `json:"genericKey,omitempty"`
	AttendanceType        any          `json:"attendanceType,omitempty"`
}
type Course struct {
	ID                          int           `json:"id,omitempty"`
	Price                       any           `json:"price,omitempty"`
	StartDate                   any           `json:"startDate,omitempty"`
	EndDate                     any           `json:"endDate,omitempty"`
	FinishDate                  any           `json:"finishDate,omitempty"`
	ObjectionStartDate          any           `json:"objectionStartDate,omitempty"`
	ObjectionEndDate            any           `json:"objectionEndDate,omitempty"`
	CourseLessonCount           any           `json:"courseLessonCount,omitempty"`
	CourseSatisfyCount          any           `json:"courseSatisfyCount,omitempty"`
	IsEnabled                   any           `json:"isEnabled,omitempty"`
	RecruitState                any           `json:"recruitState,omitempty"`
	Subject                     Subject       `json:"subject,omitempty"`
	Semester                    any           `json:"semester,omitempty"`
	Categories                  any           `json:"categories,omitempty"`
	Exam                        Exam          `json:"exam,omitempty"`
	Exams                       any           `json:"exams,omitempty"`
	Assignment                  any           `json:"assignment,omitempty"`
	Assignments                 any           `json:"assignments,omitempty"`
	Participation               any           `json:"participation,omitempty"`
	Participations              any           `json:"participations,omitempty"`
	CourseParticipations        any           `json:"courseParticipations,omitempty"`
	Lessons                     any           `json:"lessons,omitempty"`
	SatisfactionQuestions       any           `json:"satisfactionQuestions,omitempty"`
	Author                      any           `json:"author,omitempty"`
	AttendeeCount               int           `json:"attendeeCount,omitempty"`
	EndedMonth                  int           `json:"endedMonth,omitempty"`
	Percentage                  float64       `json:"percentage,omitempty"`
	ExamPapers                  any           `json:"examPapers,omitempty"`
	Clazz                       any           `json:"clazz,omitempty"`
	Managers                    any           `json:"managers,omitempty"`
	ParticipationSumScore       any           `json:"participationSumScore,omitempty"`
	Student                     any           `json:"student,omitempty"`
	MaxStudents                 any           `json:"maxStudents,omitempty"`
	Sequence                    any           `json:"sequence,omitempty"`
	IsState                     any           `json:"isState,omitempty"`
	AssignmentAllottedScore     any           `json:"assignmentAllottedScore,omitempty"`
	ParticipationAllottedScore  any           `json:"participationAllottedScore,omitempty"`
	IsChecked                   any           `json:"isChecked,omitempty"`
	PreReportCount              any           `json:"preReportCount,omitempty"`
	GradeReportCount            any           `json:"gradeReportCount,omitempty"`
	Under100Count               any           `json:"under100Count,omitempty"`
	Under90Count                any           `json:"under90Count,omitempty"`
	Under80Count                any           `json:"under80Count,omitempty"`
	Under70Count                any           `json:"under70Count,omitempty"`
	Under60Count                any           `json:"under60Count,omitempty"`
	IsInprogress                any           `json:"isInprogress,omitempty"`
	IsInprogressExam            any           `json:"isInprogressExam,omitempty"`
	Teacher                     any           `json:"teacher,omitempty"`
	DateHelper                  any           `json:"dateHelper,omitempty"`
	SimpleExamResults           any           `json:"simpleExamResults,omitempty"`
	SimpleMidTermExamResult     any           `json:"simpleMidTermExamResult,omitempty"`
	SimpleFinalTermExamResult   any           `json:"simpleFinalTermExamResult,omitempty"`
	CourseStatus                any           `json:"courseStatus,omitempty"`
	AttendeeStatus              any           `json:"attendeeStatus,omitempty"`
	EncourageAttendanceCount    any           `json:"encourageAttendanceCount,omitempty"`
	CompleteAttendanceCount     any           `json:"completeAttendanceCount,omitempty"`
	IsIngCourse                 any           `json:"isIngCourse,omitempty"`
	ParticipationCount          int           `json:"participationCount,omitempty"`
	NewID                       any           `json:"newId,omitempty"`
	NotCompletedEvaluationCount any           `json:"notCompletedEvaluationCount,omitempty"`
	IsApproval                  any           `json:"isApproval,omitempty"`
	IsAgree                     any           `json:"isAgree,omitempty"`
	GreetingStartDate           any           `json:"greetingStartDate,omitempty"`
	GreetingEndDate             any           `json:"greetingEndDate,omitempty"`
	BulletinStartDate           any           `json:"bulletinStartDate,omitempty"`
	BulletinEndDate             any           `json:"bulletinEndDate,omitempty"`
	ObjectionWorkStartDate      any           `json:"objectionWorkStartDate,omitempty"`
	ObjectionWorkEndDate        any           `json:"objectionWorkEndDate,omitempty"`
	ClassCount                  any           `json:"classCount,omitempty"`
	FinishCount                 any           `json:"finishCount,omitempty"`
	NotFinishCount              any           `json:"notFinishCount,omitempty"`
	Under100ReGrade             any           `json:"under100ReGrade,omitempty"`
	Under90ReGrade              any           `json:"under90ReGrade,omitempty"`
	Under80ReGrade              any           `json:"under80ReGrade,omitempty"`
	Under70ReGrade              any           `json:"under70ReGrade,omitempty"`
	Under60ReGrade              any           `json:"under60ReGrade,omitempty"`
	ExamCnt                     any           `json:"examCnt,omitempty"`
	IsRegular                   any           `json:"isRegular,omitempty"`
	IsNonRegular1End            any           `json:"is_non_regular_1end,omitempty"`
	IsNonRegular2End            any           `json:"is_non_regular_2end,omitempty"`
	NonRegular1EndScore         float64       `json:"non_regular_1end_score,omitempty"`
	NonRegular2EndScore         float64       `json:"non_regular_2end_score,omitempty"`
	IsSixMonth                  any           `json:"isSixMonth,omitempty"`
	MajorName                   any           `json:"majorName,omitempty"`
	MajorType                   any           `json:"majorType,omitempty"`
	Attendances                 []Attendances `json:"attendances,omitempty"`
	GenericKey                  int           `json:"genericKey,omitempty"`
	WeekProgress                int           `json:"weekProgress,omitempty"`
	CourseTitle                 any           `json:"courseTitle,omitempty"`
	FinishRatio                 float64       `json:"finishRatio,omitempty"`
	Under100Ratio               float64       `json:"under100Ratio,omitempty"`
	Under90Ratio                float64       `json:"under90Ratio,omitempty"`
	Under80Ratio                float64       `json:"under80Ratio,omitempty"`
	Under70Ratio                float64       `json:"under70Ratio,omitempty"`
	Under60Ratio                float64       `json:"under60Ratio,omitempty"`
	Under100RoundRatio          float64       `json:"under100RoundRatio,omitempty"`
	Under90RoundRatio           float64       `json:"under90RoundRatio,omitempty"`
	Under80RoundRatio           float64       `json:"under80RoundRatio,omitempty"`
	Under70RoundRatio           float64       `json:"under70RoundRatio,omitempty"`
	Under60RoundRatio           float64       `json:"under60RoundRatio,omitempty"`
}

type User struct {
	ID                     int    `json:"id,omitempty"`
	Username               string `json:"username,omitempty"`
	Password               any    `json:"password,omitempty"`
	Name                   string `json:"name,omitempty"`
	Email                  any    `json:"email,omitempty"`
	Telephone              any    `json:"telephone,omitempty"`
	Cellphone              any    `json:"cellphone,omitempty"`
	Address                any    `json:"address,omitempty"`
	LoginFailedCount       int    `json:"loginFailedCount,omitempty"`
	LastLoggedinOn         any    `json:"lastLoggedinOn,omitempty"`
	LastPasswordChangedOn  any    `json:"lastPasswordChangedOn,omitempty"`
	IsEnabled              any    `json:"isEnabled,omitempty"`
	IsLocked               any    `json:"isLocked,omitempty"`
	IsEnablePassword       any    `json:"isEnablePassword,omitempty"`
	IsDeleted              any    `json:"isDeleted,omitempty"`
	SocialSecurityNumber   any    `json:"socialSecurityNumber,omitempty"`
	Author                 any    `json:"author,omitempty"`
	IsSendEmail            any    `json:"isSendEmail,omitempty"`
	IsSendCellphone        any    `json:"isSendCellphone,omitempty"`
	SendEmailCreatedOn     any    `json:"sendEmailCreatedOn,omitempty"`
	SendCellphoneCreatedOn any    `json:"sendCellphoneCreatedOn,omitempty"`
	CetificationCreatedOn  any    `json:"cetificationCreatedOn,omitempty"`
	EmailAddress           any    `json:"emailAddress,omitempty"`
	EmailHostAddress       any    `json:"emailHostAddress,omitempty"`
	LoginDeviceType        any    `json:"loginDeviceType,omitempty"`
	UserType               any    `json:"userType,omitempty"`
	IsAdministrator        any    `json:"isAdministrator,omitempty"`
	AdminName              any    `json:"adminName,omitempty"`
	IsRested               any    `json:"isRested,omitempty"`
	RestedOn               any    `json:"restedOn,omitempty"`
	WakeUpCode             any    `json:"wakeUpCode,omitempty"`
	GenericKey             int    `json:"genericKey,omitempty"`
}

type Lesson struct {
	ID                        int    `json:"id,omitempty"`
	Title                     any    `json:"title,omitempty"`
	Topic                     any    `json:"topic,omitempty"`
	Contents                  any    `json:"contents,omitempty"`
	TeacherID                 any    `json:"teacherId,omitempty"`
	LearningTime              int    `json:"learningTime,omitempty"`
	QuestionCount             int    `json:"questionCount,omitempty"`
	TotalPages                int    `json:"totalPages,omitempty"`
	PopupWidth                int    `json:"popupWidth,omitempty"`
	PopupHeight               int    `json:"popupHeight,omitempty"`
	PcContentsPath            string `json:"pcContentsPath,omitempty"`
	MobileContentsPath        string `json:"mobileContentsPath,omitempty"`
	MobileSupportable         any    `json:"mobileSupportable,omitempty"`
	PlanFileID                any    `json:"planFileId,omitempty"`
	Mp3FileID                 any    `json:"mp3FileId,omitempty"`
	IsEnabled                 any    `json:"isEnabled,omitempty"`
	Teacher                   any    `json:"teacher,omitempty"`
	Author                    any    `json:"author,omitempty"`
	PlanFileData              any    `json:"planFileData,omitempty"`
	Mp3FileData               any    `json:"mp3FileData,omitempty"`
	Position                  any    `json:"position,omitempty"`
	AttendancePeriodStartDate any    `json:"attendancePeriodStartDate,omitempty"`
	AttendancePeriodEndDate   any    `json:"attendancePeriodEndDate,omitempty"`
	CourseLessonID            any    `json:"courseLessonId,omitempty"`
	Course                    any    `json:"course,omitempty"`
	Subjects                  any    `json:"subjects,omitempty"`
	SubjectIds                any    `json:"subjectIds,omitempty"`
	ReferenceWeek             any    `json:"referenceWeek,omitempty"`
	PopSubName                any    `json:"pop_sub_name,omitempty"`
	LearningTimeSec           any    `json:"learningTimeSec,omitempty"`
	UnEscapeTitle             any    `json:"unEscapeTitle,omitempty"`
	GenericKey                int    `json:"genericKey,omitempty"`
	UnEscapeTopic             any    `json:"unEscapeTopic,omitempty"`
	UnEscapeContents          any    `json:"unEscapeContents,omitempty"`
}

type Logs struct {
	ID                    int          `json:"id,omitempty"`
	Attendance            any          `json:"attendance,omitempty"`
	Course                Course       `json:"course,omitempty"`
	CourseLesson          CourseLesson `json:"courseLesson,omitempty"`
	User                  User         `json:"user,omitempty"`
	FinishedPage          int          `json:"finishedPage,omitempty"`
	LearningStartOn       int64        `json:"learningStartOn,omitempty"`
	LearningEndOn         int64        `json:"learningEndOn,omitempty"`
	LearningStartDate     any          `json:"learningStartDate,omitempty"`
	LearningEndDate       any          `json:"learningEndDate,omitempty"`
	FinishedLearningTime  int          `json:"finishedLearningTime,omitempty"`
	LearningDeviceType    string       `json:"learningDeviceType,omitempty"`
	IP                    string       `json:"ip,omitempty"`
	ResolvedQuestionCount int          `json:"resolvedQuestionCount,omitempty"`
	IsAutoSaved           any          `json:"isAutoSaved,omitempty"`
	ElapsedTime           int          `json:"elapsedTime,omitempty"`
	TotalFinishPages      int          `json:"totalFinishPages,omitempty"`
	IsManual              bool         `json:"isManual,omitempty"`
	IsReset               any          `json:"isReset,omitempty"`
	IsLogin               any          `json:"isLogin,omitempty"`
	GenericKey            int          `json:"genericKey,omitempty"`
}

type Standard struct {
	ID                        int    `json:"id,omitempty"`
	Position                  int    `json:"position,omitempty"`
	Lesson                    Lesson `json:"lesson,omitempty"`
	AttendancePeriodStartDate any    `json:"attendancePeriodStartDate,omitempty"`
	AttendancePeriodEndDate   any    `json:"attendancePeriodEndDate,omitempty"`
	Course                    Course `json:"course,omitempty"`
	Subject                   any    `json:"subject,omitempty"`
	Week                      any    `json:"week,omitempty"`
	DoubleWeek                any    `json:"doubleWeek,omitempty"`
	NoteCount                 any    `json:"noteCount,omitempty"`
	Notifier                  any    `json:"notifier,omitempty"`
	AttendanceType            any    `json:"attendanceType,omitempty"`
	IsInprogress              any    `json:"isInprogress,omitempty"`
	GenericKey                int    `json:"genericKey,omitempty"`
	Progressed                bool   `json:"progressed,omitempty"`
	IsPast                    any    `json:"isPast,omitempty"`
}

type Data struct {
	Course   Course   `json:"course,omitempty"`
	Logs     []Logs   `json:"logs,omitempty"`
	Standard Standard `json:"standard,omitempty"`
	LogID    int      `json:"logId,omitempty"`
}
